### ISSUE TITLE
The construction of Wikidata5m

### ISSUE THREAD

**Issue by wangbo9719** [THU-KEG/KEPLER#13]
Great work!

I have several question about the construction of Wikidata5m. 
How to align each entity in Wikidata to its Wikipedia page？And how to extract entities' descriptions? 
Did you use any off-the-shelf tools? 
Could you provide the construction codes for Wikidata5m?

Look forward to your reply! Thanks！

**Comment by Bakser** [comment]
Hi,

Thanks for your interest in our work. Sorry for that I cannot provide the original construction codes since it was a long pipeline and codes for some major steps are lost after the expiration of my account on Mila servers. I will describe the  process of constructing Wikidata5M as follows and hope this can help you:

1. Download the dumps of Wikidata (e.g. https://dumps.wikimedia.org/wikidatawiki/20211120/) and extract all the Wikidata entities and relations.

2. Download the dumps of English Wikipedia (e.g. https://dumps.wikimedia.org/enwiki/20211120/) and extract all the Wikipedia articles with [WikiExtractor](https://github.com/attardi/wikiextractor) (remember to keep the page URLs).

3. Get the corresponding English Wikipedia URL for each entity with the "wbgetentities" API and the entity id extracted in Step 1. Then use the obtained URL to find the corresponding article from the extracted results of Step 2. If we cannot get the URLs or the URLs do not show up in the English Wikipedia dump, the entities will be discarded.

4. Retrieve the first paragraph of each article selected in Step 3 as the description of each entity. Some heuristic rules to filter meaningless paragraphs are needed in this step.

**Comment by wangbo9719** [comment]
Hi, thanks for such a quick response. It's really helpful!
