### ISSUE TITLE
Continued pretraining from pytorch model

### ISSUE THREAD

**Issue by MichalPitr** [THU-KEG/KEPLER#9]
Hi, 
I'm curious, do you happen to know if there's a way to use a pre-trained model from Huggingface models and use that to initialize KEPLER training? I was hoping to initialize KEPLER with a RoBERTa pretrained on medical data and use KEPLER pretraining with medical knowledge graphs and medical MLM.

Many thanks, 
Michal

**Comment by Bakser** [comment]
Hi,
We did not try to convert Huggingface's checkpoints into fairseq checkpoints (used in KEPLER pre-training) since all our KEPLER pre-training are based on native fairseq framework. 
For your question, my suggestion is to read [this code](https://github.com/huggingface/transformers/blob/master/src/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py), which is used to convert fairseq RoBERTa checkpoints into Huggingface's and you may inversely convert it in similar way.

Best regards,
Xiaozhi

**Comment by MichalPitr** [comment]
Hi Xiozhi,
Yea, I slightly feared that would be necessary. Thanks for the confirmation!

Kind regards, 
Michal
